Document: gnomint
Title: Debian gnomint Manual
Author: <insert document author here>
Abstract: This manual describes what gnomint is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnomint/gnomint.sgml.gz

Format: postscript
Files: /usr/share/doc/gnomint/gnomint.ps.gz

Format: text
Files: /usr/share/doc/gnomint/gnomint.text.gz

Format: HTML
Index: /usr/share/doc/gnomint/html/index.html
Files: /usr/share/doc/gnomint/html/*.html

  
